"""create request_history table

Revision ID: efc8540be6a2
Revises: 1f51b890ec77
Create Date: 2025-12-22 01:42:02.140945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc8540be6a2'
down_revision: Union[str, None] = '1f51b890ec77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_history', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_history', 'answer')
    # ### end Alembic commands ###
